//Teams
export const LOAD_TEAMS_SUCCESS = 'LOAD_TEAMS_SUCCESS';
export const CREATE_TEAM_SUCCESS = 'CREATE_TEAM_SUCCESS';

//Sports
export const LOAD_SPORTS_SUCCESS = 'LOAD_SPORTS_SUCCESS';
export const CREATE_SPORT_SUCCESS = 'CREATE_SPORT_SUCCESS';

//Loading
export const CURRENTLY_LOADING = 'CURRENTLY_LOADING';

//Users
export const ACTIVE_USERS = 'ACTIVE_USERS';
