//Teams
export const LOAD_TEAMS_SUCCESS = 'LOAD_TEAMS_SUCCESS';
export const CREATE_TEAM_SUCCESS = 'CREATE_TEAM_SUCCESS';
//Team
export const LOAD_SEATING_CHART_SUCCESS = 'LOAD_SEATING_CHART_SUCCESS';

//Sports
export const LOAD_SPORTS_SUCCESS = 'LOAD_SPORTS_SUCCESS';
export const CREATE_SPORT_SUCCESS = 'CREATE_SPORT_SUCCESS';

//venues
export const LOAD_VENUES_SUCCESS = 'LOAD_VENUES_SUCCESS';
export const CREATE_VENUE_SUCCESS = 'CREATE_VENUE_SUCCESS';

//Loading
export const CURRENTLY_LOADING = 'CURRENTLY_LOADING';

//Users
export const ACTIVE_USERS = 'ACTIVE_USERS';
export const USER_ERROR = 'USER_ERROR';

export const SETTINGS = 'SETTINGS';
